# Citations

## Overview

## Questions

* What sort of things can I cite?
* How do I manage my .bib file?
* How do I change the citation style?

## Objectives

## content

 
* Articles `[@article-handle]`
  * where 
    * `article-handle` matches the article handle in the `.bib` file
    * And the bibliography is referred to in the YAML in `bibliography: filename.bib` 
  * example
  * output 
  
* Changing bibliography styles
  * PLace the appropriate Citation language style file in YAML `csl: cslfile.csl`
  * retrieve CSL output from CSL github site: 
    * example
    * output 
  
* (Advanced) Moving the bibliography
  * The bibliography is typically placed at the end of the document, so your last heading should be something like `# References`. However, if you want to move it:
  * use the `bookdown::html_document2()` output option, and then in your document, have the following structure:

```
# Introduction

# Method

# Results

# References {-}

<div id="refs"></div>

# Appendix
```

Note the reference section, the code: `<div id="refs"></div>`


This is taken from [this SO thread](https://stackoverflow.com/questions/51335125/adding-figures-and-tables-after-bibliography-in-rmarkdown?noredirect=1&lq=1). Note that the answer also states: 

> Note: this will only work if you use pandoc's built-in citation package and won't work if you set citation_package: natbib in the YAML

## Exercise {.exercise}

1. Generic exercise
