# Keyboard Shortcuts


* How to bring up the master list
* code chunk create
* knit doc
* multiple cursors
* delete line
* comment out a line (in R and in markdown)

## Overview

* **Teaching** XX minutes
* **Exercises** XX minutes

## Questions

* 

## Objectives

* 



## Common Shortcuts

Below is a small table of tasks you can perform with keyboard 

| Action      | Windows/Linux | Mac  | 
|-------------|---------------|----------------|
| Knit document | Ctrl + Shift + K | Cmd + Shift + K |
| Insert Chunk  | Ctrl + Alt + I   | Cmd + Option + I |
| Run Current Chunk | Ctrl + Alt + C | Cmd + Option + C | 
| Run Next Chunk | Ctrl + Alt + N    | Cmd + Option + N | 
| Jump to  	Shift+Alt+J 	| Cmd+Shift+Option+J |
| Show Keyboard Shortcut Reference  |	Alt+Shift+K | Option+Shift+K |

## Further Reading

- The [https://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf](Rstudio Cheat Sheet) has an index of shortcuts. 
- This [https://support.rstudio.com/hc/en-us/articles/206382178-Customizing-Keyboard-Shortcuts] help file has a guide to customising keyboard shortcuts.

## Exercises {.exercise}
- Using the Keyboard Shortcut Reference, find the keyboard shortcut for inserting a pipe character ( %>% )
