# What is Rmarkdown

* creating an rmarkdown document
* (mention in the rmarkdown part) Use HTML first, PDF/word later


* Anatomy of an rmarkdown document
  * Metadata
    - YAML
  * text
    - markdown formatting
  * code
    - code formatting
    
* What is markdown?

* inline R code
* code chunks
  * What is a backtick
  * chunk names
    * no spaces
    * give every chunk a name, it will save you time
  * chunk options
    * The ones you need to know about:
      * fig.size
      * fig.width
      * out.width
      * out.height
      * dev
      * cache
      * eval
      * echo
      * error
      * message
      * include
      * result

## Overview

* **Teaching** XX minutes
* **Exercises** XX minutes

## Questions

* 

## Objectives

* Create an rmarkdown document and do the following things.

## Exercise {.exercise}

1. Download this data file
1. Create a new rstudio project called "..."
1. Run some brief summaries of the data in the rmarkdown document
    - hist(data$)
    - How big is the data?

